### ISSUE TITLE
Vanno codificati i requisiti

### ISSUE THREAD

**Issue by bonni1207** [SWEasabi/norme-di-progetto#21]
Il codice deve contenere:
Importanza(obbligatorio/desiderabile/opzionale)
Tipologia (funzionali, di qualità, di vincolo, ...)
Codice (incrementale?)

Un esempio può essere:
R[Importanza][Tipologia][Codice]

**Comment by alessandro-massarenti** [comment]
Potresti farmi un esempio di un codice?

**Comment by bonni1207** [comment]
Un esempio può essere: R1F1
cioè, requisito di importanza 1 (obbligatorio), tipologia F (funzionale), 1 (incrementale)

**Comment by alessandro-massarenti** [comment]
Quindi va definita anche la scala di importanza?

**Comment by bonni1207** [comment]
Si, quindi potrebbe essere:
1(obbligatorio), 2(desiderabile), 3(opzionale)

**Comment by bonni1207** [comment]
Per la tipologia, potrebbe essere
F(funzionale), Q(di qualità), V(di vincolo)

**Comment by alessandro-massarenti** [comment]
> Si, quindi potrebbe essere: 1(obbligatorio), 2(desiderabile), 3(opzionale)

Quindi più è basso il numero più il requisito è importante?

Questa scala potrebbe avere variazioni in futuro?

**Comment by pierobonluca01** [comment]
Aggiornare (aggiungere la sezione relativa a) la denominazione dei requisiti come deciso in documento di Analisi dei Requisiti.
