### ISSUE TITLE
Va definita una scaletta iniziale del documento

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/norme-di-progetto#3]
Sicuramente sono da definire alcune sezioni basilari:

- lista dei cambiamenti
- Introduzione
- norme di progetto(gestione dei processi) ad esempio l'assegnazione dei ruoli, la verbalizzazione, ecc
- generalità di repository con relative labels, actions, ecc
- generalità sul setup dei documenti

@bonni1207 tu avevi in mente altre cose?
Penso che questo possa essere un lavoro per l'amministratore @pierobonluca01

**Comment by bonni1207** [comment]
Viene risolta dalle issue #12 e #13
